### ISSUE TITLE
Retry and Repeat extensions functions require addons dependencies, but they are exported as optional and so not included

### ISSUE THREAD

**Issue by agisbert** [reactor/reactor-kotlin#30]
So this happened after I generated a project with spring initializer. https://start.spring.io/ 

I added the absolute minimum dependencies in it (see pic):

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/5805538/154259837-ec4c5d18-3bfa-4288-ad30-2b822dc54a37.png">

The outcome  is the following dependencies in the pom file: 

```
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-kotlin</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.kotlin</groupId>
			<artifactId>reactor-kotlin-extensions</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-reflect</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlin</groupId>
			<artifactId>kotlin-stdlib-jdk8</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jetbrains.kotlinx</groupId>
			<artifactId>kotlinx-coroutines-reactor</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

## Motivation
So, when using any of the extension functions for retry or repeats: 

```
    fun postMovie(movie: Movie) =
        webClient
            .post()
            .uri("http://localhost:9009/movies")
            .body(Mono.just(movie))
            .retrieve()
            .toBodilessEntity()
            .retryExponentialBackoff(5, Duration.ofSeconds(1))
            .map {
                movie to true
            }.onErrorResume {
                println(it.message)
                Mono.just(movie to false)
            }
```

We get a nice NoClassDefFoundError:

```
java.lang.NoClassDefFoundError: reactor/retry/Retry
	at reactor.kotlin.extra.retry.RetryExtensionsKt.retryExponentialBackoff(RetryExtensions.kt:97) ~[reactor-kotlin-extensions-1.1.5.jar:1.1.5]
	at reactor.kotlin.extra.retry.RetryExtensionsKt.retryExponentialBackoff$default(RetryExtensions.kt:96) ~[reactor-kotlin-extensions-1.1.5.jar:1.1.5]
```

## Desired solution
reactor-extra (`optional "io.projectreactor.addons:reactor-extra:${reactorAddonsVersion}"`) is not an **optional** dependency but a **compile** one, same as reactor-core (`compile "io.projectreactor:reactor-core:${reactorCoreVersion}"`

## Considered alternatives
1. Not doing it? 
2. Refactor the extension functions so they make use of reactor-core Retry and Repeat classes (available since v3.3.3) (Probably more changes needed, haven't looked into it tbh).

**Comment by simonbasle** [comment]
that would mean doing the same for `reactor-test`. and suddenly, depending on `reactor-kotlin-extensions` eg just for the `toMono` core parts enforces a dependency on `reactor-addons` and `reactor-test`...

the situation is not great though, but this is the first time it is reported. a workaround is simply to add `reactor-extra` as a dependency, but long term solution would probably be to have separate artifacts to mirror the `reactor-core`, `reactor-adapter`, `reactor-extra` and `reactor-test` artifacts 🤔
